ems/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.schemas import get_schema_view
from django.conf.urls.static import static

from django.conf import settings


from employee.views import ( index, user_login, user_logout,
    success, ProfileUpdate, MyProfile, LoginView, LogoutView)


handler500 = 'ems.views.my_custom_error_view'


urlpatterns = [
    path('', index, name='home'),
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls', namespace="todo")),
    path('poll/', include('poll.urls')),
    path('attendance/',include('attendance.urls')),
    path('leave/',include('leave.urls')),
    #path('api/v1/', include('poll.api_urls')),
    path('api/v1/', include('employee.api_urls')),
    # path('api/v1/auth/', include('rest_auth.urls')),
    path('api/v1/auth/login/', LoginView.as_view()),
    path('api/v1/auth/logout/', LogoutView.as_view()),
    path('employee/', include('employee.urls')),

    path('login/', user_login, name="user_login"),
    path('success/', success, name="user_success"),
    path('logout/', user_logout, name="user_logout"),
    path('profile/', MyProfile.as_view(), name="my_profile"),
    path('profile/update', ProfileUpdate.as_view(), name="update_profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leave/urls.py
from django.urls import path
from .views import LeaveRequestCreate,success

app_name = 'leave'

urlpatterns = [
    path('', LeaveRequestCreate.as_view(), name = 'leaverequest_form'),
    path('success/', success ,name = 'success')
    ]

leave/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


# Create your models here.
def g():
    now = datetime.datetime.now()
    k = now.strftime("%Y-%m-%d")
    return k

def now():
        i=datetime.datetime.now()
        return i
today = now()
class LeaveRequest(models.Model):
    #name = models.OneToOneField(User,on_delete=models.CASCADE)
    reason = models.SlugField(max_length = 10,default = '')
    message = models.TextField()
    approve = models.BooleanField(default = False)
    from_date = models.DateField(default=g)
    to_date = models.DateField(default=g)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default= now)
    note = models.TextField(default = 'Pending')

    def __str__(self):
        return self.reason+'  '+self.note
    
    

ems/views.py
from django.shortcuts import render

def my_custom_error_view(request):
    return render(request,'500.html')

leave/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from .models import LeaveRequest
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponse

class LeaveRequestCreate(CreateView):
    model = LeaveRequest
    fields = ['reason','message','from_date','to_date']
    success_url = 'success/'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        if form.is_valid():
            subject = form.cleaned_data['reason']
            message = form.cleaned_data['message']+' leave from '+str(form.cleaned_data['from_date'])+' to '+str(form.cleaned_data['to_date'])
            sender = self.request.user.email

            recipients = ['dashboard.mad@gmail.com'] 
            

            send_mail(subject, message, sender, recipients)
        return super().form_valid(form)

def success(request):
    leave_request = LeaveRequest.objects.all()
    return render(request,'leave/success.html',{'leave_request':leave_request})

ems/templates/leave/leaverequest_form.html
{% extends 'base.html' %}


{% block content %}
<br>
    <form method="POST">
        {% csrf_token %}
        <table class="table table-bordered">
            {{form}}
        </table>
        <br>
        <button type="submit" class="btn btn-success float-right" readonly>Submit</button>
    </form>


<a href="{% url 'leave:success'  %}"><b>Status</b></a>

{% endblock content %}

ems/templates/leave/success.html
{% extends 'base.html' %}


{% block content %}
<br>
<p><b>LEAVE STATUS</b></p>

{% for i in leave_request %}
{% if i.approve %}
<table class="table table-light table-bordered table-striped">
        <tbody>
            <tr>
                <th>Reason/Reference</th>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Notes</th>
                
            </tr>
            <tr>
                <td>{{i.reason}}</td>
                <td>Approved</td>
				<td>{{i.created_at}}</td>
				<td>{{i.note}}</td>
            </tr>
        </tbody>
    </table>
{% else %}
<table class="table table-light table-bordered table-striped">
        <tbody>
            <tr>
                <th>Reason</th>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Notes</th>
                
            </tr>
            <tr>
                <td>{{i.reason}}</td>
                <td>..........</td>
				<td>{{i.created_at}}</td>
				<td>{{i.note}}</td>
            </tr>
        </tbody>
    </table>
{% endif %}
{% endfor %}
{% endblock %}