attendance/urls.py
from django.urls import path
from .views import AttendanceView,AttendanceList

app_name = 'attendance'

urlpatterns = [
    path('',AttendanceView.as_view(), name='attendance'),
    path('thanks/',AttendanceList.as_view() ,name = 'thanks'),
    path('salary/',sal ,name ='sal'),
    ]

ems/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.schemas import get_schema_view
from django.conf.urls.static import static

from django.conf import settings


from employee.views import ( index, user_login, user_logout,
    success, ProfileUpdate, MyProfile, LoginView, LogoutView)


handler500 = 'ems.views.my_custom_error_view'


urlpatterns = [
    path('', index, name='home'),
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls', namespace="todo")),
    path('poll/', include('poll.urls')),
    path('attendance/',include('attendance.urls')),
    path('leave/',include('leave.urls')),
    #path('api/v1/', include('poll.api_urls')),
    path('api/v1/', include('employee.api_urls')),
    # path('api/v1/auth/', include('rest_auth.urls')),
    path('api/v1/auth/login/', LoginView.as_view()),
    path('api/v1/auth/logout/', LogoutView.as_view()),
    path('employee/', include('employee.urls')),

    path('login/', user_login, name="user_login"),
    path('success/', success, name="user_success"),
    path('logout/', user_logout, name="user_logout"),
    path('profile/', MyProfile.as_view(), name="my_profile"),
    path('profile/update', ProfileUpdate.as_view(), name="update_profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leave/urls.py
from django.urls import path
from .views import LeaveRequestCreate,success

app_name = 'leave'

urlpatterns = [
    path('', LeaveRequestCreate.as_view(), name = 'leaverequest_form'),
    path('success/', success ,name = 'success')
    ]

ems/views.py
from django.shortcuts import render

def my_custom_error_view(request):
    return render(request,'500.html')

ems/templates/base.html
{% load static %}
{% block extrahead %}{% endblock extrahead %}
{% block extra_js %}{% endblock extra_js %}
<html>
    <head>
        <title>Employee Dashboard</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        
    </head>
    <body>
        {% include 'header.html'  %}
        <!-- <h1>EMS</h1> -->
        <div class="container">
            {% block content %}
			</br></br>
			
            {% endblock content %}
        </div>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

ems/templates/header.html
<div class="navbar navbar-expand-lg navbar-light bg-light">
    <span class="navbar-brand mb-0 h1">DASHBOARD</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'employee_list' %}">
                    {{"employee" | capfirst}}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'polls_list' %}">
                    {{"Polls" | capfirst}} 
                    <span class="badge badge-primary badge-pill ">{{polls_count}}</span>
                </a>
			<li class="nav-item">
                <a class="nav-link" href="{% url 'todo:lists' %}">
                    {{"Todo Lists" | capfirst}}
                </a>
            </li>
			<li class="nav-item">
                <a class="nav-link" href="{% url 'todo:mine' %}">
                    {{"My Tasks" | capfirst}}
                </a>
			<li class="nav-item">
                <a class="nav-link" href="{% url 'attendance:attendance' %}">
                    {{"Attendance" | capfirst}}
                </a>
            </li>
			<li class="nav-item">
                <a class="nav-link" href="{% url 'leave:leaverequest_form' %}">
                    {{"Leave" | capfirst}}
                </a>
            </li
        </ul>
    </div>
    <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'user_logout' %}">
        {% csrf_token %}
        <a href="{% url 'my_profile' %}">
            <span class="mr-sm-2">{{request.user.first_name}} {{request.user.last_name}}</spans>
        </a>
        <input type="submit" class="btn btn-outline-danger my-2 my-sm-0" value="Logout">
    </form>
</div>

ems/templates/welcome.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}